(test
 (name test_raw)
 (modules test_raw)
 (libraries opentui-raw windtrap))

(test
 (name test_terminal)
 (modules test_terminal)
 (libraries opentui-terminal windtrap))

(test
 (name test_terminal_modes)
 (modules test_terminal_modes)
 (libraries opentui-terminal windtrap))

(test
 (name test_terminal_input)
 (modules test_terminal_input)
 (libraries opentui-terminal windtrap))

(test
 (name test_terminal_eio)
 (modules test_terminal_eio)
 (libraries opentui-terminal-eio eio_main windtrap))

(test
 (name test_terminal_output)
 (modules test_terminal_output)
 (libraries opentui-terminal-eio eio_main eio.unix windtrap))

(test
 (name test_terminal_coordinator)
 (modules test_terminal_coordinator)
 (libraries opentui-terminal windtrap))

(test
 (name test_native)
 (modules test_native)
 (libraries opentui-native windtrap))

(library
 (name test_native_link_support)
 (modules test_native_link_support)
 (foreign_stubs
  (language c)
  (names test_native_link_stubs)
  (flags (:standard -I%{project_root}/packages/opentui-raw/native))
  (extra_deps
   ../packages/opentui-raw/native/opentui-native.stamp
   ../packages/opentui-raw/native/libopentui.dylib
   ../packages/opentui-raw/native/libopentui.so))
 (c_library_flags
  (:standard
   -Lpackages/opentui-raw/native
   -lopentui
   -Wl,-rpath,@loader_path/../packages/opentui-raw/native
   -Wl,-rpath,$ORIGIN/../packages/opentui-raw/native)))

(test
 (name test_native_link)
 (modules test_native_link)
 (libraries test_native_link_support opentui-raw windtrap))
