#ifndef OPENTUI_RAW_STATUS_H
#define OPENTUI_RAW_STATUS_H

enum opentui_raw_status {
  OPENTUI_RAW_STATUS_OK = 0,
  OPENTUI_RAW_STATUS_INVALID_ARGUMENT = 1,
  OPENTUI_RAW_STATUS_STALE_HANDLE = 2,
  OPENTUI_RAW_STATUS_NATIVE_FAILURE = 3,
  OPENTUI_RAW_STATUS_OUTPUT_TOO_SMALL = 4,
  OPENTUI_RAW_STATUS_QUEUE_OVERFLOW = 5
};

#endif
